#!/bin/bash
# Alex Trumier <adtrumier@gmail.com>

if [ "$#" -eq 0 ]; then
    echo "Usage: cless <filename>"
    exit 1
fi

if [ "$#" -ge 2 ]; then
    echo "Usaage: cless <filename>"
    exit 1
fi

cat $1 | less
